### ISSUE TITLE
openshift-applier: Allow for some method of only running portions of the inventory

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/casl-ansible#90]
For example, we may not always want to re-run certain segments of the inventory on every run, so a way to perhaps set a flag to only run certain objects within the inventory would be ideal.

@sherl0cks and @infosec812 have both been experiencing issues around this.

**Comment by sherl0cks** [comment]
This is a real challenge when maintain a source code repository with a team. What happens in practice is that people comment out sections of the inventory since its the easiest thing that works. That of course leads to all the nasty challenges associated with commented code.

I think a simple solution here is to provide a `whitelist` feature, which you can provide as variable when running the playbook. That whitelist can be a simple comma delimited list, and then the role would be enhanced to only run the `objects` in the inventory that are on the whitelist. This would give end users fine grain control of execution, without having to modify the inventory.

@InfoSec812 @oybed what do you guys think?

**Comment by InfoSec812** [comment]
I think that having a blacklist/whitelist feature would be valuable. I would suggest that we discuss at what level and how granularly to apply them though. Do we apply it at the `object` level, `object:name` level, or something else?

**Comment by oybed** [comment]
@InfoSec812 @sherl0cks This requires some discussion as it's deviates from the original plan. I'll schedule a discussion with you guys and @etsauer (once he's back from PTO).

**Comment by oybed** [comment]
@etsauer and I had a follow-up discussion tonight, and think this is a good idea overall. Eric proposed that we look to use a tag & filter strategy instead, as it allows for potential a better way of handling grouping (and more operators), so we'll work on an implementation for that. Considering that https://github.com/redhat-cop/casl-ansible/pull/102 changes the underlying structure quite a bit as well, we'll be closing out PR https://github.com/redhat-cop/casl-ansible/pull/93 and start working on the filter/tags strategy ASAP to get that working as soon as possible. 

@InfoSec812 @sherl0cks ^^
